* 
%%(org-anniversary )
* 
%%(org-anniversary )
* 
%%(org-anniversary )
* Abuela MC Maxi
%%(org-anniversary 1932-06-07)
* Academia Juli
%%(org-anniversary )
* Aire Acondicionado Onesimo
%%(org-anniversary )
* Albereto Mc Do
%%(org-anniversary )
* Alberto Cadave
%%(org-anniversary )
* Alberto Fleming
%%(org-anniversary )
* Alberto Blakberry
%%(org-anniversary )
* Alberto Ocaña
%%(org-anniversary )
* Alberto pérez
%%(org-anniversary 1979-04-12)
* Alberto Pretel Ramirez
%%(org-anniversary )
* Albuela Issa
%%(org-anniversary )
* Alca
%%(org-anniversary )
* Alcahud Dr Fleming
%%(org-anniversary )
* Ale Caro
%%(org-anniversary )
* Alejandría
%%(org-anniversary )
* Alejandro Navarro
%%(org-anniversary )
* Alex Dr Fleming
%%(org-anniversary )
* Alex Shirk
%%(org-anniversary 2015-11-06)
* Alfonso
%%(org-anniversary )
* Alicia Caro Martinez
%%(org-anniversary )
* Alicia Fleming
%%(org-anniversary )
* Alicia Ojos Madrid
%%(org-anniversary )
* Alman
%%(org-anniversary )
* Almudena Avendaño
%%(org-anniversary )
* Almudena Bornez
%%(org-anniversary )
* Almudena Negra
%%(org-anniversary )
* Alvaro Ciber
%%(org-anniversary )
* Alya Gonzalez Torres
%%(org-anniversary 1979-08-02)
* Amparo Dr Fleming
%%(org-anniversary )
* Amparo hermana Belén Bonete (Cheperudeta)
%%(org-anniversary )
* Amstid
%%(org-anniversary )
* Ana Belen Gonzalez Lopez Dr Fleming
%%(org-anniversary )
* Ana Campayo Dr Fleming
%%(org-anniversary )
* Ana Caro
%%(org-anniversary )
* Ana Laboratorio
%%(org-anniversary )
* Ana López Yeste
%%(org-anniversary )
* Ana Maria
%%(org-anniversary )
* Ana Maria1
%%(org-anniversary )
* Angel Collado
%%(org-anniversary )
* Angel Jeep
%%(org-anniversary )
* Ángeles Lloret
%%(org-anniversary )
* AnkharA
%%(org-anniversary )
* Antonia Peralta Donate
%%(org-anniversary )
* Antonio Caro
%%(org-anniversary )
* Antonio Caro 2
%%(org-anniversary )
* Antonio El Taller
%%(org-anniversary )
* Antonio Elena Ini
%%(org-anniversary )
* Antonio Lillo
%%(org-anniversary )
* Antonio Manuel Martinez Pretel, primo
%%(org-anniversary )
* Antonio‪ Oliviero, Neurólogo Hospital Nacional de Parapléjicos
%%(org-anniversary )
* Antonio TIC
%%(org-anniversary )
* Antonio Winnie
%%(org-anniversary )
* Apartamentos Isla
%%(org-anniversary )
* Aqua Jose Luis
%%(org-anniversary )
* Arantxa Olaya
%%(org-anniversary )
* Artesano. Comida Llevar
%%(org-anniversary )
* Arthan
%%(org-anniversary )
* Asgail
%%(org-anniversary )
* Atención al Cliente
%%(org-anniversary )
* Atención Al Cliente Jazztel
%%(org-anniversary )
* Bacileta Ciber
%%(org-anniversary )
* Bar La Herradura
%%(org-anniversary )
* Basi
%%(org-anniversary )
* Bea Castro Laboratorio
%%(org-anniversary )
* Beatriz CAIBER
%%(org-anniversary )
* Beatriz Moreno Acepain Psicologa
%%(org-anniversary )
* Beatriz Navarro Bravo
%%(org-anniversary 1981-07-12)
* Belen Almansa
%%(org-anniversary )
* Belen Toñin
%%(org-anniversary )
* Belinda Montalban Anestesia
%%(org-anniversary )
* Benito  De Luis Marsan
%%(org-anniversary )
* Bigote Blanco
%%(org-anniversary )
* Blanca Budapest
%%(org-anniversary )
* Blanca Residente Oncología
%%(org-anniversary )
* Blas Tic
%%(org-anniversary )
* Boilim
%%(org-anniversary )
* Buzón movis
%%(org-anniversary )
* Cadaver £
%%(org-anniversary )
* Cari Diaz Aguilar Dr Fleming
%%(org-anniversary )
* Carlos Rosa
%%(org-anniversary )
* Carmelo Hermano Pilar MC
%%(org-anniversary )
* Carmen da Casa
%%(org-anniversary )
* Carmen Dr Fleming
%%(org-anniversary )
* Carmen Mario £
%%(org-anniversary )
* Carmen Mario1£
%%(org-anniversary )
* Carmen Pretel Garrido
%%(org-anniversary 1954-08-09)
* Carmen Psiquiatra
%%(org-anniversary )
* Carole Shirk
%%(org-anniversary 2015-11-02)
* Carolina Pie Diabetico
%%(org-anniversary )
* Carolina Psiquiatría (pequeña rata)
%%(org-anniversary )
* Caronte
%%(org-anniversary )
* Carpintero Jesus Primo Angel
%%(org-anniversary )
* Carpinteroandres
%%(org-anniversary )
* Carrie Shirk
%%(org-anniversary 1984-08-15)
* Casa Alacant ¿
%%(org-anniversary )
* Casa De Oro Vereda Jaen Sushi
%%(org-anniversary )
* Casa Del Pueblo
%%(org-anniversary )
* Casa Padres
%%(org-anniversary )
* Casa  Perez Pastor
%%(org-anniversary )
* Casa Rural Cuenca
%%(org-anniversary )
* Cata Pueblo (Dani)
%%(org-anniversary )
* Centro Comercial Portal De La Marina
%%(org-anniversary )
* Centro De Salud Zona 8
%%(org-anniversary )
* Centrome Renovación Carnet Conducir
%%(org-anniversary )
* Chacha Enri
%%(org-anniversary )
* Chakal
%%(org-anniversary )
* Chary Rodríguez
%%(org-anniversary )
* Chema Pipas Dr Fleming
%%(org-anniversary )
* Chino Albacete
%%(org-anniversary )
* Chiquitina
%%(org-anniversary )
* Choclo
%%(org-anniversary )
* Choncho
%%(org-anniversary )
* Choncho Casa
%%(org-anniversary )
* Choncho Curro
%%(org-anniversary )
* Ciber
%%(org-anniversary )
* Cirix
%%(org-anniversary )
* Ciryx Casa
%%(org-anniversary )
* Clara Corcoide
%%(org-anniversary )
* Claudia Abril Cerezo Anatomía Patológica
%%(org-anniversary )
* Claudia Amiga MC
%%(org-anniversary )
* Claudia Pajarete MC
%%(org-anniversary 2011-08-14)
* Collado Kike
%%(org-anniversary )
* Compra Cocina
%%(org-anniversary )
* Comunidad Antonio Machado
%%(org-anniversary )
* Concha
%%(org-anniversary )
* Correos unidad de reparto
%%(org-anniversary )
* Corsabel Muebles La Gineta ANTONIA
%%(org-anniversary )
* Cristalero
%%(org-anniversary )
* Cristina Laboratorio
%%(org-anniversary )
* Cristina Sanchez Dr Fleming
%%(org-anniversary )
* Cristina Violonchelo
%%(org-anniversary )
* Dabra
%%(org-anniversary )
* Daena
%%(org-anniversary )
* Dani Cata Pueblo
%%(org-anniversary )
* Daniel Garcia Dr Fleming
%%(org-anniversary )
* David Shirk
%%(org-anniversary 2015-08-06)
* David TIC
%%(org-anniversary )
* Delegacion
%%(org-anniversary )
* Dentista José Emilio Muñoz
%%(org-anniversary )
* Dentista M Dolores Cuenca Losa
%%(org-anniversary )
* Devil Angel
%%(org-anniversary )
* Diana Oscar
%%(org-anniversary )
* Diego Pueblo
%%(org-anniversary )
* Dieltron
%%(org-anniversary )
* Dith
%%(org-anniversary )
* Don Cesar
%%(org-anniversary )
* Dori Perez Andres
%%(org-anniversary )
* Edu Cruz
%%(org-anniversary )
* Edwin Reparaciones
%%(org-anniversary )
* El Taller Ofimática. Antonio
%%(org-anniversary )
* Electricista Miguel Angel
%%(org-anniversary )
* Elena Caro Martinez
%%(org-anniversary )
* Elena Farmaceutica MC
%%(org-anniversary )
* Elena Ini M
%%(org-anniversary )
* Elena Iniesta
%%(org-anniversary )
* Elena Primo Javi
%%(org-anniversary )
* Elena Pueblo (Warlock)
%%(org-anniversary )
* Eleuterio
%%(org-anniversary )
* Elías Granja Alcaraz
%%(org-anniversary )
* Elias Rovira
%%(org-anniversary )
* Eliseo Dr Fleming
%%(org-anniversary )
* Emilia
%%(org-anniversary )
* Emiliate Oskar
%%(org-anniversary )
* Encarna Limpiadora
%%(org-anniversary )
* Encarni Gonzalez Lara Dr Fleming
%%(org-anniversary )
* Enrique Martinez Pretel
%%(org-anniversary )
* Enrique Popu
%%(org-anniversary )
* ESTE -> Julian Fontanero Primo De Ana
%%(org-anniversary )
* Estefania Tobarra
%%(org-anniversary )
* Ester Goonie
%%(org-anniversary )
* Ester Pueblo
%%(org-anniversary )
* Esther MMMMMM
%%(org-anniversary )
* Eva Biologa
%%(org-anniversary )
* Eva García CEIm
%%(org-anniversary )
* Evaristo
%%(org-anniversary )
* Fabian Dr Fleming
%%(org-anniversary )
* Fatima Dr Fleming
%%(org-anniversary )
* Faturalux
%%(org-anniversary )
* FCampollano
%%(org-anniversary )
* Federico Instalador
%%(org-anniversary )
* Fernando Andres Martinez
%%(org-anniversary 1954-10-30)
* Fernando Hijo María Victoria Cirugía
%%(org-anniversary )
* Fernando Martinez-Acacio
%%(org-anniversary )
* Florentino Dr Fleming
%%(org-anniversary )
* Fogon Andino (Restaurante Argentino)
%%(org-anniversary )
* Fontanero GUAY - Angel
%%(org-anniversary )
* Fontanero Marino
%%(org-anniversary )
* Fontanero. Paco
%%(org-anniversary )
* Fran Dori
%%(org-anniversary 1974-06-29)
* Fran Molina (pueblo)
%%(org-anniversary )
* Frank MC
%%(org-anniversary )
* Freud
%%(org-anniversary 1978-04-16)
* Fundación Hospital Paraplegicos
%%(org-anniversary )
* Gallud
%%(org-anniversary )
* Gelu Biobanco
%%(org-anniversary )
* Gemma S
%%(org-anniversary )
* Gerardo
%%(org-anniversary )
* Gerardo Veterinario
%%(org-anniversary )
* Gerencia Atención Primaria
%%(org-anniversary )
* Gero Anestesista
%%(org-anniversary )
* Gestoria Hipoteca BMB
%%(org-anniversary )
* Gloria Casa
%%(org-anniversary )
* Gloria Curro £
%%(org-anniversary )
* Gloria Movil ¡
%%(org-anniversary )
* Goomer
%%(org-anniversary )
* Goonie
%%(org-anniversary )
* Grandpa Shirk
%%(org-anniversary 1932-03-14)
* Guarderia
%%(org-anniversary )
* Gunkan Restaurante Sushi
%%(org-anniversary )
* Hector
%%(org-anniversary )
* Hector Elena Caro
%%(org-anniversary )
* Hospital Nive1
%%(org-anniversary )
* Hospital Nivel
%%(org-anniversary )
* Hospital Plant
%%(org-anniversary )
* Hotel Parque M
%%(org-anniversary )
* Indio, I&I, Albacete
%%(org-anniversary )
* Iberdrola Averias
%%(org-anniversary )
* Informatica Chospab
%%(org-anniversary )
* Inma Dr Fleming
%%(org-anniversary )
* Inma Torres Dr Fleming
%%(org-anniversary )
* Inmobiliaria Gómez Torres
%%(org-anniversary )
* Irene Casa
%%(org-anniversary )
* Irene Perro
%%(org-anniversary )
* Isa Alya
%%(org-anniversary )
* Isabel Monedero
%%(org-anniversary )
* Islas Hormigas Club Buceo
%%(org-anniversary )
* issa
%%(org-anniversary 1984-10-19)
* Itv
%%(org-anniversary )
* Itziar Pueblo
%%(org-anniversary )
* Jaime Gonzalez
%%(org-anniversary )
* Jaime Pueblo
%%(org-anniversary )
* Jana Alicante
%%(org-anniversary )
* Jang
%%(org-anniversary )
* 
%%(org-anniversary )
* Jaqueline
%%(org-anniversary )
* Jaro Pili
%%(org-anniversary )
* Javi Alya
%%(org-anniversary )
* Javi Chicharro
%%(org-anniversary )
* Javi Instalador Corte Ingles Cocinas
%%(org-anniversary )
* Javi Laboratorio
%%(org-anniversary )
* Javier Argandoña Dr Fleming
%%(org-anniversary )
* Javier Aroca Dr Fleming
%%(org-anniversary )
* Javier Aroca Dr Fleming
%%(org-anniversary )
* Javier Balo Carcelen Dr Fleming
%%(org-anniversary )
* Javier Navarro Dr Fleming
%%(org-anniversary )
* Jessica Wyatt Carter Luisete
%%(org-anniversary 1983-04-18)
* Jesus - Hermano de Angel Fontanero Guay
%%(org-anniversary )
* Jesus Lopez-Torres Hidalgo
%%(org-anniversary )
* Joaquin Dr Fleming
%%(org-anniversary )
* Joaquín Jordan
%%(org-anniversary )
* Joaquin Martinez Pretel
%%(org-anniversary )
* Joaquín Primo
%%(org-anniversary )
* Jordi Gen    £
%%(org-anniversary )
* Jorge Campello
%%(org-anniversary )
* Jorge Dr Fleming
%%(org-anniversary )
* Jorge Elena
%%(org-anniversary )
* Jose Albañil
%%(org-anniversary )
* Jose Ana
%%(org-anniversary )
* Jose Antonio Verdejo TINSA
%%(org-anniversary )
* Jose Antonio Yeste Dr Fleming CARPINTERO
%%(org-anniversary )
* Jose Cano De Fleming
%%(org-anniversary )
* Jose Domingo Sonia Pueblo
%%(org-anniversary )
* Jose Godinez Biobanco
%%(org-anniversary )
* José Luis Calzados España
%%(org-anniversary )
* José Manuel Casa Del Pueblo
%%(org-anniversary )
* José Miguel Latorre
%%(org-anniversary )
* José Miguel Urólogo
%%(org-anniversary )
* Joseba Rabanales Soto
%%(org-anniversary  --09-03)
* Juan Ángel Vecino
%%(org-anniversary )
* Juan Carlos Caballero Martinez
%%(org-anniversary )
* Juan Carlos Montes
%%(org-anniversary )
* Juani Pinar
%%(org-anniversary )
* Juanjo
%%(org-anniversary )
* Juli Academia
%%(org-anniversary )
* Julia
%%(org-anniversary )
* Julian Estilista Del Aluminio
%%(org-anniversary )
* Julian Monedero, Canarias
%%(org-anniversary )
* Keiji By Joel Restaurante Shushi
%%(org-anniversary )
* Kike Andres  Pretel
%%(org-anniversary )
* Kike Collado
%%(org-anniversary )
* Kiko Hermano MC
%%(org-anniversary 1975-06-08)
* KKOs
%%(org-anniversary )
* La Mazamorra Del Androide
%%(org-anniversary )
* Laia Curro
%%(org-anniversary )
* Laura Cata Pueblo
%%(org-anniversary )
* Laura Irene
%%(org-anniversary )
* Laura Ojos
%%(org-anniversary )
* Laura Valls
%%(org-anniversary )
* Leticia Serrano (Biologucha)
%%(org-anniversary )
* Lidia Dr Fleming
%%(org-anniversary )
* Linea Directa Contratacion
%%(org-anniversary )
* Lino Arquitecto
%%(org-anniversary )
* Llanetes Joseba
%%(org-anniversary )
* Llanos Alajarin
%%(org-anniversary )
* Llanos Dr Fleming
%%(org-anniversary )
* Llanos Pediatra
%%(org-anniversary )
* Lola Hospital
%%(org-anniversary )
* Lola Mujer Jaime Del Pueblo
%%(org-anniversary )
* Loli Dr Fleming
%%(org-anniversary )
* Loli Pueblo
%%(org-anniversary )
* Lorena
%%(org-anniversary )
* Lorenzo Abad Rayos
%%(org-anniversary )
* Lucas Escribano Dr Fleming
%%(org-anniversary )
* Lucia Dr Fleming
%%(org-anniversary )
* Lucia Ojos Pue
%%(org-anniversary )
* Lucio Frank
%%(org-anniversary )
* Luis Azcue Rehabilitación
%%(org-anniversary )
* Luis Enrique (Hinfil)
%%(org-anniversary )
* Luis Oncodrug
%%(org-anniversary )
* Luisete Chache
%%(org-anniversary )
* Luisma Dr Fleming
%%(org-anniversary )
* Lula. Novia De Yer
%%(org-anniversary )
* Luzbel Casa
%%(org-anniversary )
* Luzbel Movil
%%(org-anniversary )
* M Cruz Vico
%%(org-anniversary 1983-11-18)
* M Jose Bajas FUNDACION
%%(org-anniversary )
* M Jose Investigación
%%(org-anniversary )
* Macarena Pretel Ramirez
%%(org-anniversary )
* Magda Radioterapia
%%(org-anniversary )
* Mama MC
%%(org-anniversary 1955-08-21)
* Mani
%%(org-anniversary )
* Manuel Padre MC
%%(org-anniversary 1947-02-12)
* Manuel Piñan Dr Fleming
%%(org-anniversary )
* Manuel Primo
%%(org-anniversary )
* Manza
%%(org-anniversary )
* Mar Practicas Laboratorio
%%(org-anniversary )
* Mar Sal
%%(org-anniversary )
* Marcela Restrepo
%%(org-anniversary )
* Mari Carmen Soria Dr Fleming
%%(org-anniversary )
* Mari Cortes. Hija Del Mal
%%(org-anniversary )
* Maria Animalario
%%(org-anniversary )
* Maria Dolores Limpiadora
%%(org-anniversary )
* María Gómez, Dermatóloga
%%(org-anniversary )
* Maria Granada
%%(org-anniversary )
* Maria Jesús Roldan
%%(org-anniversary )
* Maria Jose Medina
%%(org-anniversary )
* Maria Lebra Bea
%%(org-anniversary )
* Maria Moreno Pretel
%%(org-anniversary )
* Maria Nieto Alonso
%%(org-anniversary )
* Maria Nuñez
%%(org-anniversary )
* María Ramón Rodríguez
%%(org-anniversary )
* Maria Residente Familia
%%(org-anniversary )
* Marian (Hermana Monica Coromoto)
%%(org-anniversary )
* Marian Diez Gonzalez
%%(org-anniversary )
* Marie Pueblo
%%(org-anniversary )
* Marieta Gerencia Atención Primaria
%%(org-anniversary )
* Marietta
%%(org-anniversary 1986-11-23)
* Marine Movil
%%(org-anniversary )
* Mario £
%%(org-anniversary )
* Marisa Primo Joaquin
%%(org-anniversary )
* Marmoles Lopez Pueblo Plato Ducha
%%(org-anniversary )
* Marta Mon Pueblo
%%(org-anniversary )
* Marta Pretel Ramirez
%%(org-anniversary 2014-11-28)
* Martita Popi
%%(org-anniversary )
* Mary Cadaver
%%(org-anniversary )
* Mary Curro   £
%%(org-anniversary )
* Mary M Otro
%%(org-anniversary )
* Mary Mov
%%(org-anniversary )
* Mary Teje
%%(org-anniversary )
* Mary1 £
%%(org-anniversary )
* Mas Ke Movil
%%(org-anniversary )
* Mauro
%%(org-anniversary )
* MC gmail
%%(org-anniversary )
* Melany
%%(org-anniversary )
* Merendero Cesar
%%(org-anniversary )
* Merendero La Hoya
%%(org-anniversary )
* Mi Oficina Sescam
%%(org-anniversary )
* Miguel Angel Madrigal Dr Fleming
%%(org-anniversary )
* Miguel Angel Martinez Pretel
%%(org-anniversary )
* Miguel Cadaver
%%(org-anniversary )
* Miguel Dr Fleming
%%(org-anniversary )
* Miguel Radiología
%%(org-anniversary )
* Mila (Edu)
%%(org-anniversary )
* Miriam Carrion Dr Fleming
%%(org-anniversary )
* Mon Pueblo
%%(org-anniversary )
* Monchi Campos
%%(org-anniversary )
* Mónica Cocoromoto
%%(org-anniversary 1979-08-02)
* Monje
%%(org-anniversary )
* MoNoNoKe (Almudena)
%%(org-anniversary )
* Morphider
%%(org-anniversary )
* Myriam Abad
%%(org-anniversary )
* Nacho Parraga Martínez
%%(org-anniversary )
* naughty{DA} Lau
%%(org-anniversary )
* Necro
%%(org-anniversary )
* Nena Melenas
%%(org-anniversary )
* Neni, Francisco Javier Nuñez Duque
%%(org-anniversary 1979-12-24)
* Nieves Jimenez Tesis
%%(org-anniversary )
* Night
%%(org-anniversary )
* Noe (Willy Pueblo)
%%(org-anniversary )
* Noemí Buceo
%%(org-anniversary )
* Nora
%%(org-anniversary )
* Nuria Miguel Angel
%%(org-anniversary )
* Nuria Teje
%%(org-anniversary )
* Olaya Jimenez Gomariz
%%(org-anniversary )
* Olvido Comunidad Vecinos
%%(org-anniversary )
* OndaCero
%%(org-anniversary )
* Optica
%%(org-anniversary )
* OSCAR GARCIA
%%(org-anniversary )
* Oscar Neurología
%%(org-anniversary )
* Oskar Garcia
%%(org-anniversary )
* Pablo Cadaver
%%(org-anniversary )
* Pablo Primo Issa
%%(org-anniversary )
* Paco
%%(org-anniversary )
* Paco Garcia Alcaraz
%%(org-anniversary )
* Paco Pepe Admi
%%(org-anniversary )
* Paco Primo Pretel
%%(org-anniversary )
* Paco1
%%(org-anniversary )
* Panaderia Reolid Paqui
%%(org-anniversary )
* Paqui Gonzalez Cuesta
%%(org-anniversary )
* Paqui Sanchez Dr Fleming
%%(org-anniversary )
* Paquito Pretel
%%(org-anniversary )
* Parking Perez Pastor
%%(org-anniversary )
* Patri £
%%(org-anniversary )
* Patricia Bajita Encantadora
%%(org-anniversary )
* Pedro Hermano MC
%%(org-anniversary 1977-05-28)
* Pedro MC
%%(org-anniversary )
* Pedro Pequeño MC
%%(org-anniversary 2015-12-01)
* Pedro Sandoval Buceo
%%(org-anniversary )
* Pedro Tarraga
%%(org-anniversary )
* Pekin
%%(org-anniversary )
* Pelli
%%(org-anniversary )
* Pelli Alicante
%%(org-anniversary )
* Pepe Peralta
%%(org-anniversary )
* Pepi Kiko Hermano MC
%%(org-anniversary 1974-06-28)
* PerfectaMenteCabrona
%%(org-anniversary )
* Perro
%%(org-anniversary )
* Pilar (cuñada) Pedro MC
%%(org-anniversary )
* Pilar Amores Valenciano (Urgencias Hospital Albacete)
%%(org-anniversary )
* Pilar Pedro Hermano MC
%%(org-anniversary 1977-10-03)
* Pilar Tarancon Cualitativa
%%(org-anniversary )
* Pili Academia
%%(org-anniversary )
* Pili Pueblo
%%(org-anniversary )
* Pintor. Pedro
%%(org-anniversary )
* Pirri
%%(org-anniversary )
* Pizzeria la mancha
%%(org-anniversary )
* Pizzeria La Mancha Albacete
%%(org-anniversary )
* Policia Objetos Perdidos
%%(org-anniversary )
* Pollo Frito Albacete Roosters
%%(org-anniversary )
* Popular
%%(org-anniversary )
* Primo Javier Pretel Ramirez
%%(org-anniversary )
* Primo Kike USA
%%(org-anniversary )
* Pris Alca Alicante
%%(org-anniversary )
* Rachel
%%(org-anniversary )
* Radio Taxi
%%(org-anniversary )
* Radio Taxi Albacete
%%(org-anniversary )
* Rafa TIC
%%(org-anniversary )
* Ramon Psico
%%(org-anniversary )
* Raquel Ester
%%(org-anniversary )
* Raquel Garcia Picazo Dr Fleming
%%(org-anniversary )
* Raquel Guardam
%%(org-anniversary )
* Raquel Necro
%%(org-anniversary )
* Raquel Pozuelo Pelirroja Dr Fleming
%%(org-anniversary )
* Raquel Vecina 1B
%%(org-anniversary )
* Raquel Villalba Dr Fleming
%%(org-anniversary )
* Raul Teva
%%(org-anniversary )
* Redstar
%%(org-anniversary )
* Restaurante Alambique Albacete
%%(org-anniversary )
* Restaurante Almagro Aromas - palacio De Los Medrano
%%(org-anniversary )
* Restaurante Arabe La Mediterranea
%%(org-anniversary )
* Restaurante Cactus Alicante Mexicano
%%(org-anniversary )
* Restaurante Gran Muralla, Alicante
%%(org-anniversary )
* Restaurante Il Forno
%%(org-anniversary )
* Restaurante La Roca
%%(org-anniversary )
* Restaurante Larruz Albacete
%%(org-anniversary )
* Restaurante Melihua, Alicante
%%(org-anniversary )
* Restaurante Pizza Angela
%%(org-anniversary )
* Restaurante Pizza Hut Alicante
%%(org-anniversary )
* Restaurante PizzaKotta
%%(org-anniversary )
* Restaurante Tagliatella
%%(org-anniversary )
* revequita
%%(org-anniversary )
* Ripper
%%(org-anniversary 1980-05-08)
* Ripper Casa
%%(org-anniversary )
* Roberto Buceo
%%(org-anniversary )
* Rocio Bonica
%%(org-anniversary )
* Rocio Night
%%(org-anniversary )
* Rosa Frías SESCAM
%%(org-anniversary )
* Ruben
%%(org-anniversary )
* Ruben Lezcano Dr Fleming
%%(org-anniversary )
* Ruben Mártinez
%%(org-anniversary )
* Salva Hermabo MJ
%%(org-anniversary )
* Salvado Galvez Dr Fleming
%%(org-anniversary )
* Sandra
%%(org-anniversary )
* Sandra Lab Hellin
%%(org-anniversary )
* Sandra Limpiad
%%(org-anniversary )
* Sandra1
%%(org-anniversary )
* Secretaria IRC
%%(org-anniversary )
* Seguro Casa
%%(org-anniversary )
* Senitox
%%(org-anniversary )
* Sephi
%%(org-anniversary )
* Sergio Fontanero Seguro
%%(org-anniversary )
* Sergio Neumologo
%%(org-anniversary )
* Sescam Bea
%%(org-anniversary )
* Sescam Docencia E Investigacion???
%%(org-anniversary )
* Sescam Investigacion
%%(org-anniversary )
* Shadyra
%%(org-anniversary )
* Silver
%%(org-anniversary )
* Silvia Dr Fleming
%%(org-anniversary )
* Silvia33
%%(org-anniversary )
* Sisebuto Carrion
%%(org-anniversary )
* Sofia
%%(org-anniversary )
* Soho Albacete Restaurante
%%(org-anniversary )
* Sonia
%%(org-anniversary )
* Squaver
%%(org-anniversary )
* Sushi Chan
%%(org-anniversary )
* Tainforma
%%(org-anniversary )
* Talleres Chinares Jeep Albacete
%%(org-anniversary )
* Tejeseta Nacho Alicante
%%(org-anniversary )
* Tele Taxi
%%(org-anniversary )
* Telepizza Albacete
%%(org-anniversary )
* Teofilo Dr Fleming
%%(org-anniversary )
* Teresa Anestesia González
%%(org-anniversary )
* Tia Dori     ¿
%%(org-anniversary )
* Tia Marien
%%(org-anniversary )
* Tia Quini Pr1¿
%%(org-anniversary )
* Tia Quini Pre¿
%%(org-anniversary )
* Tío Alberto Perez
%%(org-anniversary )
* Tio Antonio
%%(org-anniversary 1955-02-13)
* Tio Josevi Pr¿
%%(org-anniversary 1955-02-14)
* Tio Toñin
%%(org-anniversary 1969-02-10)
* Tock
%%(org-anniversary )
* Tom Shirk
%%(org-anniversary 2015-09-11)
* Tomas Navarro Dr Fleming
%%(org-anniversary )
* Tomas Segura
%%(org-anniversary )
* Tomás Vecino Bombero
%%(org-anniversary )
* Toms
%%(org-anniversary )
* Toñi Curro
%%(org-anniversary )
* Toñi Ester
%%(org-anniversary )
* Toñi Mira Mateo
%%(org-anniversary )
* Toni Rodiel
%%(org-anniversary )
* Toyota Taller
%%(org-anniversary )
* TRex Eduardo Ruiz
%%(org-anniversary )
* Trinidad Flores
%%(org-anniversary )
* Unidad De Dolor
%%(org-anniversary )
* Unidad del dolor de Albacete
%%(org-anniversary )
* Vaklav
%%(org-anniversary )
* Vaklav Casa
%%(org-anniversary )
* Valeriah
%%(org-anniversary )
* Vanesa Toledo (ayudante Antonio Olivero)
%%(org-anniversary )
* VanHell
%%(org-anniversary )
* Vanhell Casa
%%(org-anniversary )
* Ventura Pueblo
%%(org-anniversary )
* Vero Corrales
%%(org-anniversary )
* Vero Dr Fleming
%%(org-anniversary )
* Veronica
%%(org-anniversary )
* Veronica Residente Radioterapia
%%(org-anniversary )
* Vicente Dr Fleming
%%(org-anniversary )
* Vicente Isa Matemático
%%(org-anniversary )
* Vicente Parking
%%(org-anniversary )
* Vicky
%%(org-anniversary )
* Vicky Tamayo
%%(org-anniversary )
* Victoria Cirugía
%%(org-anniversary )
* Victoria Colmenero Dr Fleming
%%(org-anniversary )
* Videoclub Ibix
%%(org-anniversary )
* Viki Oscar
%%(org-anniversary )
* Virgilio Cencerrado Informática CHUA
%%(org-anniversary )
* Virgilio Informática SESCAM
%%(org-anniversary )
* Virgilio Matemáticas Uclm
%%(org-anniversary )
* Vodafone Gestión
%%(org-anniversary )
* West
%%(org-anniversary )
* Willy Pueblo
%%(org-anniversary )
* Winnie
%%(org-anniversary )
* Winnie
%%(org-anniversary 1978-04-16)
* Xhoela
%%(org-anniversary )
* Yer German Sanchez
%%(org-anniversary )
* Yessica
%%(org-anniversary )
* Yeyes
%%(org-anniversary )
* Yomis
%%(org-anniversary )
* Zalo
%%(org-anniversary )
* Zara Dr Fleming
%%(org-anniversary )
* Zeonel
%%(org-anniversary )
* 
%%(org-anniversary )
* 
%%(org-anniversary )
* 
%%(org-anniversary )
* 
%%(org-anniversary )
* Academia Juli
%%(org-anniversary )
* Aire Acondicionado Onesimo
%%(org-anniversary )
* Albereto Mc Do
%%(org-anniversary )
* Alberto Cadave
%%(org-anniversary )
* Alberto Fleming
%%(org-anniversary )
* Alberto Blakberry
%%(org-anniversary )
* Alberto Ocaña
%%(org-anniversary )
* Alberto Pretel Ramirez
%%(org-anniversary )
* Albuela Issa
%%(org-anniversary )
* Alca
%%(org-anniversary )
* Alcahud Dr Fleming
%%(org-anniversary )
* Ale Caro
%%(org-anniversary )
* Alejandría
%%(org-anniversary )
* Alejandro Navarro
%%(org-anniversary )
* Alex Dr Fleming
%%(org-anniversary )
* Alfonso
%%(org-anniversary )
* Alicia Caro Martinez
%%(org-anniversary )
* Alicia Fleming
%%(org-anniversary )
* Alicia Ojos Madrid
%%(org-anniversary )
* Alman
%%(org-anniversary )
* Almudena Avendaño
%%(org-anniversary )
* Almudena Bornez
%%(org-anniversary )
* Almudena Negra
%%(org-anniversary )
* Alvaro Ciber
%%(org-anniversary )
* Amparo Dr Fleming
%%(org-anniversary )
* Amparo hermana Belén Bonete (Cheperudeta)
%%(org-anniversary )
* Amstid
%%(org-anniversary )
* Ana Belen Gonzalez Lopez Dr Fleming
%%(org-anniversary )
* Ana Campayo Dr Fleming
%%(org-anniversary )
* Ana Caro
%%(org-anniversary )
* Ana Laboratorio
%%(org-anniversary )
* Ana López Yeste
%%(org-anniversary )
* Ana Maria
%%(org-anniversary )
* Ana Maria1
%%(org-anniversary )
* Angel Collado
%%(org-anniversary )
* Angel Jeep
%%(org-anniversary )
* Ángeles Lloret
%%(org-anniversary )
* AnkharA
%%(org-anniversary )
* Antonia Peralta Donate
%%(org-anniversary )
* Antonio Caro
%%(org-anniversary )
* Antonio Caro 2
%%(org-anniversary )
* Antonio El Taller
%%(org-anniversary )
* Antonio Elena Ini
%%(org-anniversary )
* Antonio Lillo
%%(org-anniversary )
* Antonio Manuel Martinez Pretel, primo
%%(org-anniversary )
* Antonio‪ Oliviero, Neurólogo Hospital Nacional de Parapléjicos
%%(org-anniversary )
* Antonio TIC
%%(org-anniversary )
* Antonio Winnie
%%(org-anniversary )
* Apartamentos Isla
%%(org-anniversary )
* Aqua Jose Luis
%%(org-anniversary )
* Arantxa Olaya
%%(org-anniversary )
* Artesano. Comida Llevar
%%(org-anniversary )
* Arthan
%%(org-anniversary )
* Asgail
%%(org-anniversary )
* Atención al Cliente
%%(org-anniversary )
* Atención Al Cliente Jazztel
%%(org-anniversary )
* Bacileta Ciber
%%(org-anniversary )
* Bar La Herradura
%%(org-anniversary )
* Basi
%%(org-anniversary )
* Bea Castro Laboratorio
%%(org-anniversary )
* Beatriz CAIBER
%%(org-anniversary )
* Beatriz Moreno Acepain Psicologa
%%(org-anniversary )
* Belen Almansa
%%(org-anniversary )
* Belen Toñin
%%(org-anniversary )
* Belinda Montalban Anestesia
%%(org-anniversary )
* Benito  De Luis Marsan
%%(org-anniversary )
* Bigote Blanco
%%(org-anniversary )
* Blanca Budapest
%%(org-anniversary )
* Blanca Residente Oncología
%%(org-anniversary )
* Blas Tic
%%(org-anniversary )
* Boilim
%%(org-anniversary )
* Buzón movis
%%(org-anniversary )
* Cadaver £
%%(org-anniversary )
* Cari Diaz Aguilar Dr Fleming
%%(org-anniversary )
* Carlos Rosa
%%(org-anniversary )
* Carmelo Hermano Pilar MC
%%(org-anniversary )
* Carmen da Casa
%%(org-anniversary )
* Carmen Dr Fleming
%%(org-anniversary )
* Carmen Mario £
%%(org-anniversary )
* Carmen Mario1£
%%(org-anniversary )
* Carmen Psiquiatra
%%(org-anniversary )
* Carolina Pie Diabetico
%%(org-anniversary )
* Carolina Psiquiatría (pequeña rata)
%%(org-anniversary )
* Caronte
%%(org-anniversary )
* Carpintero Jesus Primo Angel
%%(org-anniversary )
* Carpinteroandres
%%(org-anniversary )
* Casa Alacant ¿
%%(org-anniversary )
* Casa De Oro Vereda Jaen Sushi
%%(org-anniversary )
* Casa Del Pueblo
%%(org-anniversary )
* Casa Padres
%%(org-anniversary )
* Casa  Perez Pastor
%%(org-anniversary )
* Casa Rural Cuenca
%%(org-anniversary )
* Cata Pueblo (Dani)
%%(org-anniversary )
* Centro Comercial Portal De La Marina
%%(org-anniversary )
* Centro De Salud Zona 8
%%(org-anniversary )
* Centrome Renovación Carnet Conducir
%%(org-anniversary )
* Chacha Enri
%%(org-anniversary )
* Chakal
%%(org-anniversary )
* Chary Rodríguez
%%(org-anniversary )
* Chema Pipas Dr Fleming
%%(org-anniversary )
* Chino Albacete
%%(org-anniversary )
* Chiquitina
%%(org-anniversary )
* Choclo
%%(org-anniversary )
* Choncho
%%(org-anniversary )
* Choncho Casa
%%(org-anniversary )
* Choncho Curro
%%(org-anniversary )
* Ciber
%%(org-anniversary )
* Cirix
%%(org-anniversary )
* Ciryx Casa
%%(org-anniversary )
* Clara Corcoide
%%(org-anniversary )
* Claudia Abril Cerezo Anatomía Patológica
%%(org-anniversary )
* Claudia Amiga MC
%%(org-anniversary )
* Collado Kike
%%(org-anniversary )
* Compra Cocina
%%(org-anniversary )
* Comunidad Antonio Machado
%%(org-anniversary )
* Concha
%%(org-anniversary )
* Correos unidad de reparto
%%(org-anniversary )
* Corsabel Muebles La Gineta ANTONIA
%%(org-anniversary )
* Cristalero
%%(org-anniversary )
* Cristina Laboratorio
%%(org-anniversary )
* Cristina Sanchez Dr Fleming
%%(org-anniversary )
* Cristina Violonchelo
%%(org-anniversary )
* Dabra
%%(org-anniversary )
* Daena
%%(org-anniversary )
* Dani Cata Pueblo
%%(org-anniversary )
* Daniel Garcia Dr Fleming
%%(org-anniversary )
* David TIC
%%(org-anniversary )
* Delegacion
%%(org-anniversary )
* Dentista José Emilio Muñoz
%%(org-anniversary )
* Dentista M Dolores Cuenca Losa
%%(org-anniversary )
* Devil Angel
%%(org-anniversary )
* Diana Oscar
%%(org-anniversary )
* Diego Pueblo
%%(org-anniversary )
* Dieltron
%%(org-anniversary )
* Dith
%%(org-anniversary )
* Don Cesar
%%(org-anniversary )
* Dori Perez Andres
%%(org-anniversary )
* Edu Cruz
%%(org-anniversary )
* Edwin Reparaciones
%%(org-anniversary )
* El Taller Ofimática. Antonio
%%(org-anniversary )
* Electricista Miguel Angel
%%(org-anniversary )
* Elena Caro Martinez
%%(org-anniversary )
* Elena Farmaceutica MC
%%(org-anniversary )
* Elena Ini M
%%(org-anniversary )
* Elena Iniesta
%%(org-anniversary )
* Elena Primo Javi
%%(org-anniversary )
* Elena Pueblo (Warlock)
%%(org-anniversary )
* Eleuterio
%%(org-anniversary )
* Elías Granja Alcaraz
%%(org-anniversary )
* Elias Rovira
%%(org-anniversary )
* Eliseo Dr Fleming
%%(org-anniversary )
* Emilia
%%(org-anniversary )
* Emiliate Oskar
%%(org-anniversary )
* Encarna Limpiadora
%%(org-anniversary )
* Encarni Gonzalez Lara Dr Fleming
%%(org-anniversary )
* Enrique Martinez Pretel
%%(org-anniversary )
* Enrique Popu
%%(org-anniversary )
* ESTE -> Julian Fontanero Primo De Ana
%%(org-anniversary )
* Estefania Tobarra
%%(org-anniversary )
* Ester Goonie
%%(org-anniversary )
* Ester Pueblo
%%(org-anniversary )
* Esther MMMMMM
%%(org-anniversary )
* Eva Biologa
%%(org-anniversary )
* Eva García CEIm
%%(org-anniversary )
* Evaristo
%%(org-anniversary )
* Fabian Dr Fleming
%%(org-anniversary )
* Fatima Dr Fleming
%%(org-anniversary )
* Faturalux
%%(org-anniversary )
* FCampollano
%%(org-anniversary )
* Federico Instalador
%%(org-anniversary )
* Fernando Hijo María Victoria Cirugía
%%(org-anniversary )
* Fernando Martinez-Acacio
%%(org-anniversary )
* Florentino Dr Fleming
%%(org-anniversary )
* Fogon Andino (Restaurante Argentino)
%%(org-anniversary )
* Fontanero GUAY - Angel
%%(org-anniversary )
* Fontanero Marino
%%(org-anniversary )
* Fontanero. Paco
%%(org-anniversary )
* Fran Molina (pueblo)
%%(org-anniversary )
* Frank MC
%%(org-anniversary )
* Fundación Hospital Paraplegicos
%%(org-anniversary )
* Gallud
%%(org-anniversary )
* Gelu Biobanco
%%(org-anniversary )
* Gemma S
%%(org-anniversary )
* Gerardo
%%(org-anniversary )
* Gerardo Veterinario
%%(org-anniversary )
* Gerencia Atención Primaria
%%(org-anniversary )
* Gero Anestesista
%%(org-anniversary )
* Gestoria Hipoteca BMB
%%(org-anniversary )
* Gloria Casa
%%(org-anniversary )
* Gloria Curro £
%%(org-anniversary )
* Gloria Movil ¡
%%(org-anniversary )
* Goomer
%%(org-anniversary )
* Goonie
%%(org-anniversary )
* Guarderia
%%(org-anniversary )
* Gunkan Restaurante Sushi
%%(org-anniversary )
* Hector
%%(org-anniversary )
* Hector Elena Caro
%%(org-anniversary )
* Hospital Nive1
%%(org-anniversary )
* Hospital Nivel
%%(org-anniversary )
* Hospital Plant
%%(org-anniversary )
* Hotel Parque M
%%(org-anniversary )
* Indio, I&I, Albacete
%%(org-anniversary )
* Iberdrola Averias
%%(org-anniversary )
* Informatica Chospab
%%(org-anniversary )
* Inma Dr Fleming
%%(org-anniversary )
* Inma Torres Dr Fleming
%%(org-anniversary )
* Inmobiliaria Gómez Torres
%%(org-anniversary )
* Irene Casa
%%(org-anniversary )
* Irene Perro
%%(org-anniversary )
* Isa Alya
%%(org-anniversary )
* Isabel Monedero
%%(org-anniversary )
* Islas Hormigas Club Buceo
%%(org-anniversary )
* Itv
%%(org-anniversary )
* Itziar Pueblo
%%(org-anniversary )
* Jaime Gonzalez
%%(org-anniversary )
* Jaime Pueblo
%%(org-anniversary )
* Jana Alicante
%%(org-anniversary )
* Jang
%%(org-anniversary )
* 
%%(org-anniversary )
* Jaqueline
%%(org-anniversary )
* Jaro Pili
%%(org-anniversary )
* Javi Alya
%%(org-anniversary )
* Javi Chicharro
%%(org-anniversary )
* Javi Instalador Corte Ingles Cocinas
%%(org-anniversary )
* Javi Laboratorio
%%(org-anniversary )
* Javier Argandoña Dr Fleming
%%(org-anniversary )
* Javier Aroca Dr Fleming
%%(org-anniversary )
* Javier Aroca Dr Fleming
%%(org-anniversary )
* Javier Balo Carcelen Dr Fleming
%%(org-anniversary )
* Javier Navarro Dr Fleming
%%(org-anniversary )
* Jesus - Hermano de Angel Fontanero Guay
%%(org-anniversary )
* Jesus Lopez-Torres Hidalgo
%%(org-anniversary )
* Joaquin Dr Fleming
%%(org-anniversary )
* Joaquín Jordan
%%(org-anniversary )
* Joaquin Martinez Pretel
%%(org-anniversary )
* Joaquín Primo
%%(org-anniversary )
* Jordi Gen    £
%%(org-anniversary )
* Jorge Campello
%%(org-anniversary )
* Jorge Dr Fleming
%%(org-anniversary )
* Jorge Elena
%%(org-anniversary )
* Jose Albañil
%%(org-anniversary )
* Jose Ana
%%(org-anniversary )
* Jose Antonio Verdejo TINSA
%%(org-anniversary )
* Jose Antonio Yeste Dr Fleming CARPINTERO
%%(org-anniversary )
* Jose Cano De Fleming
%%(org-anniversary )
* Jose Domingo Sonia Pueblo
%%(org-anniversary )
* Jose Godinez Biobanco
%%(org-anniversary )
* José Luis Calzados España
%%(org-anniversary )
* José Manuel Casa Del Pueblo
%%(org-anniversary )
* José Miguel Latorre
%%(org-anniversary )
* José Miguel Urólogo
%%(org-anniversary )
* Juan Ángel Vecino
%%(org-anniversary )
* Juan Carlos Caballero Martinez
%%(org-anniversary )
* Juan Carlos Montes
%%(org-anniversary )
* Juani Pinar
%%(org-anniversary )
* Juanjo
%%(org-anniversary )
* Juli Academia
%%(org-anniversary )
* Julia
%%(org-anniversary )
* Julian Estilista Del Aluminio
%%(org-anniversary )
* Julian Monedero, Canarias
%%(org-anniversary )
* Keiji By Joel Restaurante Shushi
%%(org-anniversary )
* Kike Andres  Pretel
%%(org-anniversary )
* Kike Collado
%%(org-anniversary )
* KKOs
%%(org-anniversary )
* La Mazamorra Del Androide
%%(org-anniversary )
* Laia Curro
%%(org-anniversary )
* Laura Cata Pueblo
%%(org-anniversary )
* Laura Irene
%%(org-anniversary )
* Laura Ojos
%%(org-anniversary )
* Laura Valls
%%(org-anniversary )
* Leticia Serrano (Biologucha)
%%(org-anniversary )
* Lidia Dr Fleming
%%(org-anniversary )
* Linea Directa Contratacion
%%(org-anniversary )
* Lino Arquitecto
%%(org-anniversary )
* Llanetes Joseba
%%(org-anniversary )
* Llanos Alajarin
%%(org-anniversary )
* Llanos Dr Fleming
%%(org-anniversary )
* Llanos Pediatra
%%(org-anniversary )
* Lola Hospital
%%(org-anniversary )
* Lola Mujer Jaime Del Pueblo
%%(org-anniversary )
* Loli Dr Fleming
%%(org-anniversary )
* Loli Pueblo
%%(org-anniversary )
* Lorena
%%(org-anniversary )
* Lorenzo Abad Rayos
%%(org-anniversary )
* Lucas Escribano Dr Fleming
%%(org-anniversary )
* Lucia Dr Fleming
%%(org-anniversary )
* Lucia Ojos Pue
%%(org-anniversary )
* Lucio Frank
%%(org-anniversary )
* Luis Azcue Rehabilitación
%%(org-anniversary )
* Luis Enrique (Hinfil)
%%(org-anniversary )
* Luis Oncodrug
%%(org-anniversary )
* Luisete Chache
%%(org-anniversary )
* Luisma Dr Fleming
%%(org-anniversary )
* Lula. Novia De Yer
%%(org-anniversary )
* Luzbel Casa
%%(org-anniversary )
* Luzbel Movil
%%(org-anniversary )
* M Jose Bajas FUNDACION
%%(org-anniversary )
* M Jose Investigación
%%(org-anniversary )
* Macarena Pretel Ramirez
%%(org-anniversary )
* Magda Radioterapia
%%(org-anniversary )
* Mani
%%(org-anniversary )
* Manuel Piñan Dr Fleming
%%(org-anniversary )
* Manuel Primo
%%(org-anniversary )
* Manza
%%(org-anniversary )
* Mar Practicas Laboratorio
%%(org-anniversary )
* Mar Sal
%%(org-anniversary )
* Marcela Restrepo
%%(org-anniversary )
* Mari Carmen Soria Dr Fleming
%%(org-anniversary )
* Mari Cortes. Hija Del Mal
%%(org-anniversary )
* Maria Animalario
%%(org-anniversary )
* Maria Dolores Limpiadora
%%(org-anniversary )
* María Gómez, Dermatóloga
%%(org-anniversary )
* Maria Granada
%%(org-anniversary )
* Maria Jesús Roldan
%%(org-anniversary )
* Maria Jose Medina
%%(org-anniversary )
* Maria Lebra Bea
%%(org-anniversary )
* Maria Moreno Pretel
%%(org-anniversary )
* Maria Nieto Alonso
%%(org-anniversary )
* Maria Nuñez
%%(org-anniversary )
* María Ramón Rodríguez
%%(org-anniversary )
* Maria Residente Familia
%%(org-anniversary )
* Marian (Hermana Monica Coromoto)
%%(org-anniversary )
* Marian Diez Gonzalez
%%(org-anniversary )
* Marie Pueblo
%%(org-anniversary )
* Marieta Gerencia Atención Primaria
%%(org-anniversary )
* Marine Movil
%%(org-anniversary )
* Mario £
%%(org-anniversary )
* Marisa Primo Joaquin
%%(org-anniversary )
* Marmoles Lopez Pueblo Plato Ducha
%%(org-anniversary )
* Marta Mon Pueblo
%%(org-anniversary )
* Martita Popi
%%(org-anniversary )
* Mary Cadaver
%%(org-anniversary )
* Mary Curro   £
%%(org-anniversary )
* Mary M Otro
%%(org-anniversary )
* Mary Mov
%%(org-anniversary )
* Mary Teje
%%(org-anniversary )
* Mary1 £
%%(org-anniversary )
* Mas Ke Movil
%%(org-anniversary )
* Mauro
%%(org-anniversary )
* MC gmail
%%(org-anniversary )
* Melany
%%(org-anniversary )
* Merendero Cesar
%%(org-anniversary )
* Merendero La Hoya
%%(org-anniversary )
* Mi Oficina Sescam
%%(org-anniversary )
* Miguel Angel Madrigal Dr Fleming
%%(org-anniversary )
* Miguel Angel Martinez Pretel
%%(org-anniversary )
* Miguel Cadaver
%%(org-anniversary )
* Miguel Dr Fleming
%%(org-anniversary )
* Miguel Radiología
%%(org-anniversary )
* Mila (Edu)
%%(org-anniversary )
* Miriam Carrion Dr Fleming
%%(org-anniversary )
* Mon Pueblo
%%(org-anniversary )
* Monchi Campos
%%(org-anniversary )
* Monje
%%(org-anniversary )
* MoNoNoKe (Almudena)
%%(org-anniversary )
* Morphider
%%(org-anniversary )
* Myriam Abad
%%(org-anniversary )
* Nacho Parraga Martínez
%%(org-anniversary )
* naughty{DA} Lau
%%(org-anniversary )
* Necro
%%(org-anniversary )
* Nena Melenas
%%(org-anniversary )
* Nieves Jimenez Tesis
%%(org-anniversary )
* Night
%%(org-anniversary )
* Noe (Willy Pueblo)
%%(org-anniversary )
* Noemí Buceo
%%(org-anniversary )
* Nora
%%(org-anniversary )
* Nuria Miguel Angel
%%(org-anniversary )
* Nuria Teje
%%(org-anniversary )
* Olaya Jimenez Gomariz
%%(org-anniversary )
* Olvido Comunidad Vecinos
%%(org-anniversary )
* OndaCero
%%(org-anniversary )
* Optica
%%(org-anniversary )
* OSCAR GARCIA
%%(org-anniversary )
* Oscar Neurología
%%(org-anniversary )
* Oskar Garcia
%%(org-anniversary )
* Pablo Cadaver
%%(org-anniversary )
* Pablo Primo Issa
%%(org-anniversary )
* Paco
%%(org-anniversary )
* Paco Garcia Alcaraz
%%(org-anniversary )
* Paco Pepe Admi
%%(org-anniversary )
* Paco Primo Pretel
%%(org-anniversary )
* Paco1
%%(org-anniversary )
* Panaderia Reolid Paqui
%%(org-anniversary )
* Paqui Gonzalez Cuesta
%%(org-anniversary )
* Paqui Sanchez Dr Fleming
%%(org-anniversary )
* Paquito Pretel
%%(org-anniversary )
* Parking Perez Pastor
%%(org-anniversary )
* Patri £
%%(org-anniversary )
* Patricia Bajita Encantadora
%%(org-anniversary )
* Pedro MC
%%(org-anniversary )
* Pedro Sandoval Buceo
%%(org-anniversary )
* Pedro Tarraga
%%(org-anniversary )
* Pekin
%%(org-anniversary )
* Pelli
%%(org-anniversary )
* Pelli Alicante
%%(org-anniversary )
* Pepe Peralta
%%(org-anniversary )
* PerfectaMenteCabrona
%%(org-anniversary )
* Perro
%%(org-anniversary )
* Pilar (cuñada) Pedro MC
%%(org-anniversary )
* Pilar Amores Valenciano (Urgencias Hospital Albacete)
%%(org-anniversary )
* Pilar Tarancon Cualitativa
%%(org-anniversary )
* Pili Academia
%%(org-anniversary )
* Pili Pueblo
%%(org-anniversary )
* Pintor. Pedro
%%(org-anniversary )
* Pirri
%%(org-anniversary )
* Pizzeria la mancha
%%(org-anniversary )
* Pizzeria La Mancha Albacete
%%(org-anniversary )
* Policia Objetos Perdidos
%%(org-anniversary )
* Pollo Frito Albacete Roosters
%%(org-anniversary )
* Popular
%%(org-anniversary )
* Primo Javier Pretel Ramirez
%%(org-anniversary )
* Primo Kike USA
%%(org-anniversary )
* Pris Alca Alicante
%%(org-anniversary )
* Rachel
%%(org-anniversary )
* Radio Taxi
%%(org-anniversary )
* Radio Taxi Albacete
%%(org-anniversary )
* Rafa TIC
%%(org-anniversary )
* Ramon Psico
%%(org-anniversary )
* Raquel Ester
%%(org-anniversary )
* Raquel Garcia Picazo Dr Fleming
%%(org-anniversary )
* Raquel Guardam
%%(org-anniversary )
* Raquel Necro
%%(org-anniversary )
* Raquel Pozuelo Pelirroja Dr Fleming
%%(org-anniversary )
* Raquel Vecina 1B
%%(org-anniversary )
* Raquel Villalba Dr Fleming
%%(org-anniversary )
* Raul Teva
%%(org-anniversary )
* Redstar
%%(org-anniversary )
* Restaurante Alambique Albacete
%%(org-anniversary )
* Restaurante Almagro Aromas - palacio De Los Medrano
%%(org-anniversary )
* Restaurante Arabe La Mediterranea
%%(org-anniversary )
* Restaurante Cactus Alicante Mexicano
%%(org-anniversary )
* Restaurante Gran Muralla, Alicante
%%(org-anniversary )
* Restaurante Il Forno
%%(org-anniversary )
* Restaurante La Roca
%%(org-anniversary )
* Restaurante Larruz Albacete
%%(org-anniversary )
* Restaurante Melihua, Alicante
%%(org-anniversary )
* Restaurante Pizza Angela
%%(org-anniversary )
* Restaurante Pizza Hut Alicante
%%(org-anniversary )
* Restaurante PizzaKotta
%%(org-anniversary )
* Restaurante Tagliatella
%%(org-anniversary )
* revequita
%%(org-anniversary )
* Ripper Casa
%%(org-anniversary )
* Roberto Buceo
%%(org-anniversary )
* Rocio Bonica
%%(org-anniversary )
* Rocio Night
%%(org-anniversary )
* Rosa Frías SESCAM
%%(org-anniversary )
* Ruben
%%(org-anniversary )
* Ruben Lezcano Dr Fleming
%%(org-anniversary )
* Ruben Mártinez
%%(org-anniversary )
* Salva Hermabo MJ
%%(org-anniversary )
* Salvado Galvez Dr Fleming
%%(org-anniversary )
* Sandra
%%(org-anniversary )
* Sandra Lab Hellin
%%(org-anniversary )
* Sandra Limpiad
%%(org-anniversary )
* Sandra1
%%(org-anniversary )
* Secretaria IRC
%%(org-anniversary )
* Seguro Casa
%%(org-anniversary )
* Senitox
%%(org-anniversary )
* Sephi
%%(org-anniversary )
* Sergio Fontanero Seguro
%%(org-anniversary )
* Sergio Neumologo
%%(org-anniversary )
* Sescam Bea
%%(org-anniversary )
* Sescam Docencia E Investigacion???
%%(org-anniversary )
* Sescam Investigacion
%%(org-anniversary )
* Shadyra
%%(org-anniversary )
* Silver
%%(org-anniversary )
* Silvia Dr Fleming
%%(org-anniversary )
* Silvia33
%%(org-anniversary )
* Sisebuto Carrion
%%(org-anniversary )
* Sofia
%%(org-anniversary )
* Soho Albacete Restaurante
%%(org-anniversary )
* Sonia
%%(org-anniversary )
* Squaver
%%(org-anniversary )
* Sushi Chan
%%(org-anniversary )
* Tainforma
%%(org-anniversary )
* Talleres Chinares Jeep Albacete
%%(org-anniversary )
* Tejeseta Nacho Alicante
%%(org-anniversary )
* Tele Taxi
%%(org-anniversary )
* Telepizza Albacete
%%(org-anniversary )
* Teofilo Dr Fleming
%%(org-anniversary )
* Teresa Anestesia González
%%(org-anniversary )
* Tia Dori     ¿
%%(org-anniversary )
* Tia Marien
%%(org-anniversary )
* Tia Quini Pr1¿
%%(org-anniversary )
* Tia Quini Pre¿
%%(org-anniversary )
* Tío Alberto Perez
%%(org-anniversary )
* Tock
%%(org-anniversary )
* Tomas Navarro Dr Fleming
%%(org-anniversary )
* Tomas Segura
%%(org-anniversary )
* Tomás Vecino Bombero
%%(org-anniversary )
* Toms
%%(org-anniversary )
* Toñi Curro
%%(org-anniversary )
* Toñi Ester
%%(org-anniversary )
* Toñi Mira Mateo
%%(org-anniversary )
* Toni Rodiel
%%(org-anniversary )
* Toyota Taller
%%(org-anniversary )
* TRex Eduardo Ruiz
%%(org-anniversary )
* Trinidad Flores
%%(org-anniversary )
* Unidad De Dolor
%%(org-anniversary )
* Unidad del dolor de Albacete
%%(org-anniversary )
* Vaklav
%%(org-anniversary )
* Vaklav Casa
%%(org-anniversary )
* Valeriah
%%(org-anniversary )
* Vanesa Toledo (ayudante Antonio Olivero)
%%(org-anniversary )
* VanHell
%%(org-anniversary )
* Vanhell Casa
%%(org-anniversary )
* Ventura Pueblo
%%(org-anniversary )
* Vero Corrales
%%(org-anniversary )
* Vero Dr Fleming
%%(org-anniversary )
* Veronica
%%(org-anniversary )
* Veronica Residente Radioterapia
%%(org-anniversary )
* Vicente Dr Fleming
%%(org-anniversary )
* Vicente Isa Matemático
%%(org-anniversary )
* Vicente Parking
%%(org-anniversary )
* Vicky
%%(org-anniversary )
* Vicky Tamayo
%%(org-anniversary )
* Victoria Cirugía
%%(org-anniversary )
* Victoria Colmenero Dr Fleming
%%(org-anniversary )
* Videoclub Ibix
%%(org-anniversary )
* Viki Oscar
%%(org-anniversary )
* Virgilio Cencerrado Informática CHUA
%%(org-anniversary )
* Virgilio Informática SESCAM
%%(org-anniversary )
* Virgilio Matemáticas Uclm
%%(org-anniversary )
* Vodafone Gestión
%%(org-anniversary )
* West
%%(org-anniversary )
* Willy Pueblo
%%(org-anniversary )
* Winnie
%%(org-anniversary )
* Xhoela
%%(org-anniversary )
* Yer German Sanchez
%%(org-anniversary )
* Yessica
%%(org-anniversary )
* Yeyes
%%(org-anniversary )
* Yomis
%%(org-anniversary )
* Zalo
%%(org-anniversary )
* Zara Dr Fleming
%%(org-anniversary )
* Zeonel
%%(org-anniversary )
* 
%%(org-anniversary )
* Abuela MC Maxi
%%(org-anniversary 1932-06-07)
* Alberto pérez
%%(org-anniversary 1979-04-12)
* Alex Shirk
%%(org-anniversary 2015-11-06)
* Alya Gonzalez Torres
%%(org-anniversary 1979-08-02)
* Beatriz Navarro Bravo
%%(org-anniversary 1981-07-12)
* Carmen Pretel Garrido
%%(org-anniversary 1954-08-09)
* Carole Shirk
%%(org-anniversary 2015-11-02)
* Carrie Shirk
%%(org-anniversary 1984-08-15)
* Claudia Pajarete MC
%%(org-anniversary 2011-08-14)
* David Shirk
%%(org-anniversary 2015-08-06)
* Fernando Andres Martinez
%%(org-anniversary 1954-10-30)
* Fran Dori
%%(org-anniversary 1974-06-29)
* Freud
%%(org-anniversary 1978-04-16)
* Grandpa Shirk
%%(org-anniversary 1932-03-14)
* issa
%%(org-anniversary 1984-10-19)
* Jessica Wyatt Carter Luisete
%%(org-anniversary 1983-04-18)
* Joseba Rabanales Soto
%%(org-anniversary  --09-03)
* Kiko Hermano MC
%%(org-anniversary 1975-06-08)
* M Cruz Vico
%%(org-anniversary 1983-11-18)
* Mama MC
%%(org-anniversary 1955-08-21)
* Manuel Padre MC
%%(org-anniversary 1947-02-12)
* Marietta
%%(org-anniversary 1986-11-23)
* Marta Pretel Ramirez
%%(org-anniversary 2014-11-28)
* Mónica Cocoromoto
%%(org-anniversary 1979-08-02)
* Neni, Francisco Javier Nuñez Duque
%%(org-anniversary 1979-12-24)
* Pedro Hermano MC
%%(org-anniversary 1977-05-28)
* Pedro Pequeño MC
%%(org-anniversary 2015-12-01)
* Pepi Kiko Hermano MC
%%(org-anniversary 1974-06-28)
* Pilar Pedro Hermano MC
%%(org-anniversary 1977-10-03)
* Ripper
%%(org-anniversary 1980-05-08)
* Tio Antonio
%%(org-anniversary 1955-02-13)
* Tio Josevi Pr¿
%%(org-anniversary 1955-02-14)
* Tio Toñin
%%(org-anniversary 1969-02-10)
* Tom Shirk
%%(org-anniversary 2015-09-11)
* Winnie
%%(org-anniversary 1978-04-16)
* Abuela MC Maxi
%%(org-anniversary 1932-06-07)
* Alberto pérez
%%(org-anniversary 1979-04-12)
* Alex Shirk
%%(org-anniversary 2015-11-06)
* Alya Gonzalez Torres
%%(org-anniversary 1979-08-02)
* Beatriz Navarro Bravo
%%(org-anniversary 1981-07-12)
* Carmen Pretel Garrido
%%(org-anniversary 1954-08-09)
* Carole Shirk
%%(org-anniversary 2015-11-02)
* Carrie Shirk
%%(org-anniversary 1984-08-15)
* Claudia Pajarete MC
%%(org-anniversary 2011-08-14)
* David Shirk
%%(org-anniversary 2015-08-06)
* Fernando Andres Martinez
%%(org-anniversary 1954-10-30)
* Fran Dori
%%(org-anniversary 1974-06-29)
* Freud
%%(org-anniversary 1978-04-16)
* Grandpa Shirk
%%(org-anniversary 1932-03-14)
* issa
%%(org-anniversary 1984-10-19)
* Jessica Wyatt Carter Luisete
%%(org-anniversary 1983-04-18)
* Joseba Rabanales Soto
%%(org-anniversary  --09-03)
* Kiko Hermano MC
%%(org-anniversary 1975-06-08)
* M Cruz Vico
%%(org-anniversary 1983-11-18)
* Mama MC
%%(org-anniversary 1955-08-21)
* Manuel Padre MC
%%(org-anniversary 1947-02-12)
* Marietta
%%(org-anniversary 1986-11-23)
* Marta Pretel Ramirez
%%(org-anniversary 2014-11-28)
* Mónica Cocoromoto
%%(org-anniversary 1979-08-02)
* Neni, Francisco Javier Nuñez Duque
%%(org-anniversary 1979-12-24)
* Pedro Hermano MC
%%(org-anniversary 1977-05-28)
* Pedro Pequeño MC
%%(org-anniversary 2015-12-01)
* Pepi Kiko Hermano MC
%%(org-anniversary 1974-06-28)
* Pilar Pedro Hermano MC
%%(org-anniversary 1977-10-03)
* Ripper
%%(org-anniversary 1980-05-08)
* Tio Antonio
%%(org-anniversary 1955-02-13)
* Tio Josevi Pr¿
%%(org-anniversary 1955-02-14)
* Tio Toñin
%%(org-anniversary 1969-02-10)
* Tom Shirk
%%(org-anniversary 2015-09-11)
* Winnie
%%(org-anniversary 1978-04-16)
* Abuela MC Maxi
%%(org-anniversary 1932 06 07)
* Alberto pérez
%%(org-anniversary 1979 04 12)
* Alex Shirk
%%(org-anniversary 2015 11 06)
* Alya Gonzalez Torres
%%(org-anniversary 1979 08 02)
* Beatriz Navarro Bravo
%%(org-anniversary 1981 07 12)
* Carmen Pretel Garrido
%%(org-anniversary 1954 08 09)
* Carole Shirk
%%(org-anniversary 2015 11 02)
* Carrie Shirk
%%(org-anniversary 1984 08 15)
* Claudia Pajarete MC
%%(org-anniversary 2011 08 14)
* David Shirk
%%(org-anniversary 2015 08 06)
* Fernando Andres Martinez
%%(org-anniversary 1954 10 30)
* Fran Dori
%%(org-anniversary 1974 06 29)
* Freud
%%(org-anniversary 1978 04 16)
* Grandpa Shirk
%%(org-anniversary 1932 03 14)
* issa
%%(org-anniversary 1984 10 19)
* Jessica Wyatt Carter Luisete
%%(org-anniversary 1983 04 18)
* Joseba Rabanales Soto
%%(org-anniversary    09)
* Kiko Hermano MC
%%(org-anniversary 1975 06 08)
* M Cruz Vico
%%(org-anniversary 1983 11 18)
* Mama MC
%%(org-anniversary 1955 08 21)
* Manuel Padre MC
%%(org-anniversary 1947 02 12)
* Marietta
%%(org-anniversary 1986 11 23)
* Marta Pretel Ramirez
%%(org-anniversary 2014 11 28)
* Mónica Cocoromoto
%%(org-anniversary 1979 08 02)
* Neni, Francisco Javier Nuñez Duque
%%(org-anniversary 1979 12 24)
* Pedro Hermano MC
%%(org-anniversary 1977 05 28)
* Pedro Pequeño MC
%%(org-anniversary 2015 12 01)
* Pepi Kiko Hermano MC
%%(org-anniversary 1974 06 28)
* Pilar Pedro Hermano MC
%%(org-anniversary 1977 10 03)
* Ripper
%%(org-anniversary 1980 05 08)
* Tio Antonio
%%(org-anniversary 1955 02 13)
* Tio Josevi Pr¿
%%(org-anniversary 1955 02 14)
* Tio Toñin
%%(org-anniversary 1969 02 10)
* Tom Shirk
%%(org-anniversary 2015 09 11)
* Winnie
%%(org-anniversary 1978 04 16)
