#! /bin/sh

#---- keybindings
killall sxhkd &
sxhkd &

#---- compositing
killall -q picom
picom &

#---- wallpapers
killall -q nitrogen
nitrogen --restore &



#---- arrancamos polkit para poder usar pamac, si no se queja de que falla al identificación de root
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &

 #--------- nombre de los monitores con xrandr -q | grep -w connected
if [[ $(hostname) == 'hades' ]]; then
    #IZQ
    bspc monitor DVI-D-0  -d 8 9 0

    #CENTRAL
    bspc monitor HDMI-0 -d 1 2 3 4
    #DERECHA
    bspc monitor DVI-I-0 -d 5 6 7

elif [[ $(hostname) == 'udaicfernando' ]]; then
    #IZQ
    bspc monitor DVI-I-0 -d 1 2 3 4
    #DRCHO
    bspc monitor HDMI-0 -d 8 9 0
fi

#---- polybar
sh ~/.config/polybar/bspwm/polybar_launcher.sh

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  4
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr

if [[$(hostname) == 'hades']]; then
    # xdo below -t $(xdo id -n root) $(xdo id -a polybar-top_HDMI-0)
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-top_aux_DVI-I-0)
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-top_aux_DVI-D-0)

    xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n polybar-top_HDMI-0)

elif [[ $(hostname) == 'udaicfernando']]; then
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-top_aux_HDMI-0)
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-top_DVI-I-0)
    #xdo below -t $(xdo id -n root) $(xdo id -a polybar-top_aux_DVI-D-0)
fi

#bspc rule -a '*:yad' state=floating follow=on focus=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='8'
#bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

