#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="${DIR:-$BLOCK_INSTANCE}"
DIR="${DIR:-$HOME}"
ALERT_LOW="${ALERT_LOW:-$1}"
ALERT_LOW="${ALERT_LOW:-10}" # color will turn red under this value (default: 10%)

LOCAL_FLAG="-l"
if [ "$1" = "-n" ] || [ "$2" = "-n" ]; then
	LOCAL_FLAG=""
fi

DISK=$(df -h -P $LOCAL_FLAG "$DIR" | awk -v label="$LABEL" -v alert_low=$ALERT_LOW '
/\/.*/ {
	device = $1
	disk_total = $2
	disk_total_used = $3
	disk_folder = $4
	disk_used_percent = $5
	# full text
	# print label $4

	# short text
	# print label $4

	# use=$5

	# no need to continue parsing
	exit 0
}

END {
	# gsub(/%$/,"",use)
	# if (100 - use < alert_low) {
	# 	# color
	# 	print "#FF0000"
	# }
	printf("%.1iG/%1iG (%.f%%)", disk_total_used, disk_total, disk_used_percent)
}
')

LABEL=$my_label
FG_COLOR=$fg_color
BG_COLOR=$bg_color
echo "<span background='${BG_COLOR}' foreground='${FG_COLOR}'> ${LABEL} ${DISK}     </span>"
# echo "<span foreground='#FFFFFF'> AAAAAAA </span>"
