#!/usr/bin/env perl
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
# Copyright 2014 Benjamin Chretien <chretien at lirmm dot fr>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use utf8;
use Getopt::Long;

# binmode(STDOUT, ":utf8");
# BEGIN {
#     binmode STDIN,  ':encoding(UTF-8)';
#     binmode STDOUT, ':encoding(UTF-8)';
#     binmode STDERR, ':encoding(UTF-8)';
# }
# default values
my $t_warn = $ENV{T_WARN} || 70;
my $t_crit = $ENV{T_CRIT} || 90;
my $chip = $ENV{SENSOR_CHIP} || "";
my $temperature = -9999;
my $label_normal = $ENV{my_label_normal} // "TEMP: ";
my $label_warning = $ENV{my_label_warning} // "TEMP: ";
my $label_alert = $ENV{my_label_alert} // "TEMP: ";
my $decimals = $ENV{DECIMALS} // 2;
my $fg_color_normal = $ENV{fg_color_normal} // "#000000";
my $fg_color_alert= $ENV{fg_color_alert} // "#FF0000";
my $fg_color_warning= $ENV{fg_color_warning} // "#FFCC00";
my $bg_color_normal = $ENV{bg_color_normal} // "#999999";
my $bg_color_warning= $ENV{bg_color_normal} // "#999999";
my $bg_color_alert= $ENV{bg_color_normal} // "#999999";

sub help {
    print "Usage: temperature [-w <warning>] [-c <critical>] [--chip <chip>]\n";
    print "-w <percent>: warning threshold to become yellow\n";
    print "-c <percent>: critical threshold to become red\n";
    print "--chip <chip>: sensor chip\n";
    exit 0;
}

GetOptions("help|h" => \&help,
           "w=i"    => \$t_warn,
           "c=i"    => \$t_crit,
           "chip=s" => \$chip);

# Get chip temperature
$ENV{LC_ALL_BACK} = $ENV{LC_ALL}; # -- Guardamos la variable de entorno sobre idioma
$ENV{LC_ALL}="en_US"; # if mpstat is not run under en_US locale, things may break, so make sure it is
open (SENSORS, "sensors -u $chip |") or die;
while (<SENSORS>) {
    if (/^\s+temp1_input:\s+[\+]*([\-]*\d+\.\d)/) {
        $temperature = $1;
        last;
    }
}
close(SENSORS);

$ENV{LC_ALL} = $ENV{LC_ALL_BACK};

$temperature eq -9999 and die 'Cannot find temperature';

# Print short_text, full_text
# print "$temperature°C\n" x2;

# Print color, if needed
if ($temperature >= $t_crit) {
    printf "<span background='${bg_color_alert}' foreground='${fg_color_alert}'>${label_alert}%.${decimals}f C   </span>\n", $temperature;
    exit 33;

    # print "#FF0000\n";
    # exit 33;
} elsif ($temperature >= $t_warn) {
    printf "<span background='${bg_color_warning}' foreground='${fg_color_warning}'>${label_warning}%.${decimals}f C   </span>\n", $temperature;
    # print "#FFFC00\n";
} else {
    printf "<span background='${bg_color_normal}' foreground='${fg_color_normal}'>${label_normal}%.${decimals}f C   </span>\n", $temperature;

}

exit 0;
